feat: CLI to check whether caret-rclcpp is used
tier4/ros2caret pull request #1
Opened 2022-04-15 06:44 UTC by atsushi421

[CARET/rclcpp が適用されてビルドしているか確認するためのツール作成](https://tier4.atlassian.net/browse/T4PB-16473) が完了したので、ご確認をお願いいたします。
 
logger の設定等は caret_analyze を参考にして書きました。
コマンドの実行完了までに1分程度かかります。

2022-04-15 07:45 UTC, hsgwa requested changes

2022-04-15 07:45 UTC, hsgwa commented on ros2caret/verb/check_caret_rclcpp.py
> +            help='the path to the directory to be checked', required=True)
実際にはcheck_directoryの/build/ 以下がチェックされるので少し分かりにくいように思いました。

例として以下のような変更ではいかがでしょうか？
- 引数名変更： --workspace 変更
-  helpメッセージ変更：「確認するワークスペースへのパス」

2022-04-15 07:45 UTC, hsgwa commented on ros2caret/verb/check_caret_rclcpp.py
> +        if(os.path.exists(root_dir_path)):
issueだと追えなくなるので、アイデア等もコメントに残していただいて大丈夫です。
以下を英語のコメントで残して頂けないでしょうか？
- Autowareを対象に行うと1min程度かかる。要高速化

2022-04-15 07:45 UTC, hsgwa commented on ros2caret/verb/check_caret_rclcpp.py
> +            logger.error('Specify the path to the directory where the build command completed.')
「buildディレクトリが見つかりませんでした。」の文書を追加お願いします。
build commandを行ったパスも「ワークスペースのパス」という風に統一をお願いします。

2022-04-17 21:19 UTC, atsushi421 commented
@hsgwa 
お疲れ様です。
指摘していただいた事項を修正しましたので、ご確認をお願いいたします。

2022-04-18 05:35 UTC, hsgwa approved these changes
LGTM

2022-04-18 05:36 UTC, merged