fix(check_caret_rclcpp): skip check_caret_rclcpp for ROS Distributions after iron
tier4/ros2caret pull request #135
Opened 2023-10-27 09:58 UTC by ymski

## Description

In humble, application is need to rebuild with caret-rclcpp when traceing and evaluating the data.
After iron some trace points have been added to the ros2-caret, therefore it is no longer necessary to check if you are building with caret-rclcpp.
If a build validation command `ros2 caret check_caret_rclcpp` is performed, the process is skipped and and exit successfully.

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [x] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-12-22 02:34 UTC, isp-uetsuki requested changes

2023-12-22 02:34 UTC, isp-uetsuki commented on ros2caret/verb/check_caret_rclcpp.py
> +                    'Thus, there is no need to validate the workspace.')
I suggest mor simple message like:
`There is no need to build packages using caret-rclcpp under ROS 2 $ROS_DISTRO.`

2023-12-25 01:03 UTC, ymski commented on ros2caret/verb/check_caret_rclcpp.py
> +                    'Thus, there is no need to validate the workspace.')
@isp-uetsuki 
I think the message you suggest is a better message.
Fixed in [45eeff7](https://github.com/tier4/ros2caret/pull/135/commits/45eeff78fab77f7b256b803290345982f0126682)

2023-12-25 01:19 UTC, isp-uetsuki approved these changes
LGTM

2023-12-27 02:36 UTC, merged