feat: multihost
tier4/ros2caret pull request #163
Opened 2023-12-26 06:46 UTC by ymski

## Description

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2024-01-19 03:15 UTC, isp-uetsuki requested changes

2024-01-19 03:15 UTC, isp-uetsuki commented on ros2caret/verb/record.py
> +        ps = subprocess.run(command, shell=True, capture_output=True, text=True)
Are `capture_output=True` and `text=True` necessary? If they are not, I suggest removing them.

2024-01-19 08:51 UTC, ymski commented on ros2caret/verb/record.py
> +        ps = subprocess.run(command, shell=True, capture_output=True, text=True)
remove options in [ad468ea](https://github.com/tier4/ros2caret/pull/163/commits/ad468eada1a706aa4d9f962b9c838a0d00da3f1a).

2024-01-24 01:01 UTC, ymski commented on ros2caret/verb/chain_latency.py
> +                      validate=isinstance(args.trace_directory, list))
@isp-uetsuki 
Thanks for reviewing.
Referring to the following document, it appears that `args.trace_directory` is a list type even when a single directory is passed to the -t option.
- https://docs.python.org/3/library/argparse.html#nargs

I have actually run it and confirmed that it works as expected.

2024-01-25 06:50 UTC, isp-uetsuki commented on ros2caret/verb/chain_latency.py
> +                      validate=isinstance(args.trace_directory, list))
Can you also apply following changes?

> - please change message_flow.py and summary.py as the same manner.
> - please change type of trace_dir argument of CreateArchitecture.__init__ to list[str].

2024-01-29 07:20 UTC, isp-uetsuki commented
LGTM

2024-03-18 02:06 UTC, isp-uetsuki approved these changes
LGTM

2024-05-10 08:21 UTC, xygyo77 approved these changes
LGTM

2024-05-10 08:40 UTC, merged