fix: add max_construction_order to the command line argument
tier4/ros2caret pull request #173
Opened 2024-02-22 11:31 UTC by xygyo77

## Description

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2024-02-27 04:47 UTC, isp-uetsuki requested changes
I suggest changing max_construction_order to max_callback_construction_order_on_path_searching to represent its function clealy.

2024-02-27 10:43 UTC, isp-uetsuki requested changes

2024-02-27 10:43 UTC, isp-uetsuki commented on ros2caret/verb/check_ctf.py
> +                 'The value must be positive integer. "0" is unlimited.',
I suggest changing help message as below. If you agree this change, please apply same change to another files.

```suggestion
            help='callbacks whose construction_order are greater than this value are ignored on path searching.'
                 'The value must be positive integer or "0". "0" means unlimited.',
```

2024-02-27 10:43 UTC, isp-uetsuki commented on ros2caret/verb/check_ctf.py
> +            required=False, default=None)
I suggest changing `default` to 10 and simplify `main()` as:

```
    def main(self, *, args):
        try:
            Lttng(args.trace_dir)
            Architecture('lttng', args.trace_dir, args.max_callback_construction_order_on_path_searching)
        except Error as e:
            logger.warning(e)
```

 If you agree this change, please apply same change to another files.

2024-02-27 10:43 UTC, isp-uetsuki commented on ros2caret/verb/check_caret_rclcpp.py
Can you revert change of this file? I think this change is not necessary.
If this is result of auto correction and difficult to revert, please let me know.

2024-02-27 10:43 UTC, isp-uetsuki commented on ros2caret/verb/create_architecture.py
> +        raise e
Can you revert this unnecessary change?

2024-02-27 10:43 UTC, isp-uetsuki commented on ros2caret/verb/verify_paths.py
> +        raise e
Can you revert this unnecessary change?

2024-02-28 03:32 UTC, xygyo77 commented on ros2caret/verb/check_ctf.py
> +                 'The value must be positive integer. "0" is unlimited.',
consent

2024-02-28 03:45 UTC, xygyo77 commented on ros2caret/verb/check_ctf.py
> +            required=False, default=None)
I think you need to check for None or a positive number greater than or equal to 0.

2024-02-28 04:29 UTC, xygyo77 commented on ros2caret/verb/check_caret_rclcpp.py
I'll put it back in; I think the PEP8 error was causing me to modify unrelated parts of the file as well.

2024-02-28 04:29 UTC, xygyo77 commented on ros2caret/verb/create_architecture.py
> +        raise e
I agree.

2024-02-28 04:37 UTC, xygyo77 commented on ros2caret/verb/check_ctf.py
> +            required=False, default=None)
We believe that the default value follows the caret_analyze implementation, so it is better to be able to omit arguments in the command.

2024-03-01 06:57 UTC, isp-uetsuki requested changes

2024-03-01 06:57 UTC, isp-uetsuki commented on ros2caret/verb/create_architecture.py
> +                )
I suggest removing `tmp`.

```suggestion
                self._arch = Architecture(
                    'lttng',
                    trace_dir,
                    max_callback_construction_order_on_path_searching
                )
```

2024-03-01 06:57 UTC, isp-uetsuki commented on ros2caret/verb/create_architecture.py
> +        return 0
I suggest removing `return` because another `main` methods in this package do not have explicit `return`.

```suggestion
```

2024-03-01 06:57 UTC, isp-uetsuki commented on ros2caret/verb/verify_paths.py
> +        return 0
I suggest removing `return` because another main methods in this package do not have explicit `return`.

```suggestion
```

2024-03-01 06:57 UTC, isp-uetsuki commented on test/verb/__init__.py
Can you remove this file? This file is added by this PR, but I think this is not necessary.

2024-03-01 07:17 UTC, xygyo77 commented on ros2caret/verb/create_architecture.py
> +                )
consent.

2024-03-01 07:20 UTC, xygyo77 commented on ros2caret/verb/create_architecture.py
> +        return 0
I agree.

2024-03-01 07:33 UTC, xygyo77 commented on ros2caret/verb/verify_paths.py
> +        return 0
I agree.

2024-03-01 07:37 UTC, xygyo77 commented on test/verb/__init__.py
I agree.

2024-03-01 07:59 UTC, isp-uetsuki approved these changes
LGTM

2024-03-04 22:10 UTC, miyakoshi-dev approved these changes
LGTM

2024-03-05 04:21 UTC, merged