feat: add filtering option to summary
tier4/ros2caret pull request #20
Opened 2022-07-03 23:17 UTC by atsushi421

@hsgwa @takam5f2 
[T4PB-18091 測定後の一括チェックツールに測定に関する情報を出力できるようにする](https://tier4.atlassian.net/browse/T4PB-18091?atlOrigin=eyJpIjoiYTgxMTgzYzBjNzQzNGM5Nzk1NTc4ZTE0NmFiN2JlOWQiLCJwIjoiamlyYS1zbGFjay1pbnQifQ) チケットの作業が完了したので、ご確認をお願いいたします。
node_summar, topic_summary, trace_point_summary に共通する処理は、Summary クラスにまとめました。

以下は再現に必要なファイルです。
- [検証用コード(ipynb)](https://drive.google.com/file/d/1_mPyTmVFDYHhARDdIR6f-O53vsKK0mKD/view?usp=sharing)
- [検証に使用したトレースデータ](https://drive.google.com/file/d/1ktKgyGJJ09qLu4LjoIFY4p7xvukxiaIf/view?usp=sharing)
- [検証用コードの出力結果(HTML)](https://drive.google.com/file/d/1JFqcp_Uxlnb9WGSQ2WKuRrDuGde-Ocga/view?usp=sharing)

2022-07-05 02:01 UTC, hsgwa requested changes

2022-07-05 02:01 UTC, hsgwa commented on ros2caret/verb/summary.py
> +        print(Summary._get_trace_creation_datetime(args.trace_dir))
_get_measure_durationと_get_trace_creation_datetimeは機能追加としてCARET_analyzeのLttngクラスに追加をお願いできますでしょうか？

ros2caretは、可能なだけCARET_analyzeのCLI向けの薄いラッパーにしたいです。

2022-07-05 07:58 UTC, atsushi421 commented on ros2caret/verb/summary.py
> +        print('\n')
分離いたしました

2022-07-05 07:58 UTC, atsushi421 commented on ros2caret/verb/summary.py
> +    ) -> List[Optional[LttngEventFilter]]:
リンクを貼っていただいた箇所に一致するよう修正いたしました。

2022-07-05 08:03 UTC, atsushi421 commented on ros2caret/verb/summary.py
> +        print(Summary._get_trace_creation_datetime(args.trace_dir))
Lttngクラスに追加させていただきました。
PR は以下です。
https://github.com/tier4/CARET_analyze/pull/80

2022-07-05 08:14 UTC, atsushi421 commented
@hsgwa 
指摘していただいた事項を修正したので、もう一度ご確認をお願いいたします。
出力結果は修正前と変わらないことを確認しました。
（[こちらの検証コード](https://github.com/tier4/ros2caret/pull/20#issue-1292445829) で検証可能です）

2022-07-11 09:09 UTC, atsushi421 commented
@hsgwa 
pytest が通るようになりました。ありがとうございます！
お時間ある時に review お願いいたします。

2022-07-13 09:26 UTC, hsgwa commented on ros2caret/verb/summary.py
> +        print('\n')
スミマセン、コメントが適切でなかったです。
分離した上で、コンストラクタから_print_summaryを呼ばず、Summary.print()関数を外から呼ぶようにおねがいできますでしょうか？

2022-07-13 09:28 UTC, hsgwa commented on ros2caret/verb/summary.py
> +    ) -> List[Optional[LttngEventFilter]]:
「LttngクラスはOptional[List]を受け付ける」という話なだけですので、
_get_filtersはList[LttngEventFilter]を返却するという風にしてしまって良いです。

```
return filters or None
```
ここも、特に or Noneが実行されることは無さそうですので、`return filters`で良いと思います。

2022-07-15 03:35 UTC, hsgwa approved these changes
LGTM!

2022-07-15 03:35 UTC, merged