feat: create and verify architecture file
tier4/ros2caret pull request #25
Opened 2022-07-20 23:31 UTC by atsushi421

[ros2 caret の CLI でアーキテクチャファイルの作成・チェックを可能にする](https://tier4.atlassian.net/browse/T4PB-17111) の作業が完了したので、ご確認をお願いいたします。

再現に必要なファイルを添付させていただきます。
- [テストコード出力結果 HTML](https://drive.google.com/file/d/1J7hM0baEVe4_rOeNEiCUqF__aLDqwQeX/view?usp=sharing)
- [テストコード (ipynb)](https://drive.google.com/file/d/1uUUQ2Zr64091dE91mS5ZMo028SNejMqp/view?usp=sharing)
- [テストコードで使用したトレースデータ](https://drive.google.com/file/d/1Yi0D9RIy23rTIFYkw_wfYul46Y-J_kZy/view?usp=sharing)
- [テストコードで使用したアーキテクチャファイル](https://drive.google.com/file/d/1ThnJxndzl8mMyyEvLP8WkxRjd8ccABw7/view?usp=sharing)

2022-07-21 00:43 UTC, hsgwa requested changes

2022-07-21 00:43 UTC, hsgwa commented on ros2caret/verb/verify_paths.py
> +                logger.info('No problem.')
もう少し踏み込んで「path_nameのレイテンシを算出できます。」という旨も一緒に出力をお願いできますでしょうか？

2022-07-21 00:43 UTC, hsgwa commented on test/verb/test_create_architecture.py
> +    def test_check_created_01(self, caplog, mocker):
01だと、テストが失敗した時に実装を見る必要が出てしますので、
もう少し”後で思い出せる”ぐらいの命名にしていただけると助かります。
「exist_case」「not_exist_case」みたいなのはいかがでしょうか？

2022-07-21 00:43 UTC, hsgwa commented on ros2caret/verb/create_architecture.py
> +        CreateArchitecture._check_created(output_path)
これはtry-exceptで記述をお願いします。
場合によってはexportで例外が飛び、_check_createdが呼ばれないこともあります。

2022-07-21 00:43 UTC, hsgwa commented on ros2caret/verb/create_architecture.py
> +        arch.export(output_path)
コンストラクタはインスタンスの生成に徹したほうが流れが追いやすいです。
exportはメンバ関数として外だしをお願いします。

または、これぐらいであれば、コンストラクタにせずに単に関数にしても良いかもしれません。

2022-07-21 08:16 UTC, atsushi421 commented
@hsgwa 
指摘していただいた事項を修正いたしました。
ご確認をお願いいたします。

2022-07-21 08:18 UTC, atsushi421 commented on ros2caret/verb/create_architecture.py
> +        CreateArchitecture._check_created(output_path)
_check_created を実行する意図で、エラーをログ出力に変換したのですが、flake8 で警告が出てしまいます。
エラー内容はそのまま出力しているので、現状のコードで大丈夫でしょうか。

2022-07-22 04:50 UTC, atsushi421 commented on ros2caret/verb/create_architecture.py
> +        CreateArchitecture._check_created(output_path)
解決いたしました

2022-07-25 06:24 UTC, hsgwa requested changes
確認お願いします。

2022-07-25 06:24 UTC, hsgwa commented on ros2caret/verb/create_architecture.py
> +        self._output_path = output_path
output_pathはコンストラクタの引数ではなく、create関数の引数にお願いできますでしょうか？

2022-07-25 06:24 UTC, hsgwa commented on ros2caret/verb/create_architecture.py
> +        parser.add_argument(
アーキテクチャファイルの上書きを許容する「forceオプション」も対応をお願いできますでしょうか？
forceオプションはexport関数が既に対応しています。

https://github.com/tier4/CARET_analyze/blob/main/src/caret_analyze/architecture/architecture.py#L146

2022-07-25 06:24 UTC, hsgwa commented on ros2caret/verb/verify_paths.py
> +        verified_path_names: Optional[List[str]]
verified_path_namesはverify関数の引数に変更をお願いできますでしょうか？

[関数の引数で足りるデータをインスタンス変数にしない](https://qiita.com/alt_yamamoto/items/25eda376e6b947208996#%E9%96%A2%E6%95%B0%E3%81%AE%E5%BC%95%E6%95%B0%E3%81%A7%E8%B6%B3%E3%82%8A%E3%82%8B%E3%83%87%E3%83%BC%E3%82%BF%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%82%BF%E3%83%B3%E3%82%B9%E5%A4%89%E6%95%B0%E3%81%AB%E3%81%97%E3%81%AA%E3%81%84)

2022-07-25 06:24 UTC, hsgwa commented on ros2caret/verb/create_architecture.py
> +        CreateArchitecture._check_created(self._output_path)
ここでチェックをすると、
1. create成功
2. create失敗→ファイルは既にあるので成功のメッセージが出る
となってしまいます。

2022-07-25 06:24 UTC, hsgwa commented on ros2caret/verb/verify_paths.py
> +        verified_path_names: Optional[List[str]]
例えば、ArchitectureクラスをVerifyPathsのコンストラクタにoptionで与えるのはいかがでしょうか？
NoneであればArchitectureを使うようにし、
テスト時にMockのArchitectureクラスを受け取った際にはMockでArchitectureクラスをインスタンス化する流れです。

2022-07-25 06:24 UTC, hsgwa commented on test/verb/test_create_architecture.py
> +        CreateArchitecture._check_created('')
これはCARET_analyzeを実装して反省している所でもあり、特に変更しなくても良いですがコメントです。


可能なレベルであれば、CreateArchitectureは公開されているインターフェースだけでテストケースを書いたほうが、変化に強いテストケースになります。

_check_createdを単体でテストするのであれば、_check_createdの戻り値をモックで上書きするようにして、
別途CreateArchitectureのテストをしたほうが良いです。

2022-07-25 11:44 UTC, atsushi421 commented
@hsgwa 
チェックありがとうございます。
指摘して頂いた事項を修正しましたので、ご確認をお願いいたします。

2022-07-26 06:45 UTC, hsgwa approved these changes
LGTM!

2022-07-26 06:46 UTC, hsgwa approved these changes

2022-07-26 06:46 UTC, merged