feat(record): support runtime recording
tier4/ros2caret pull request #48
Opened 2022-11-01 07:44 UTC by hsgwa

Signed-off-by: hsgwa <19860128+hsgwa@users.noreply.github.com>

2022-11-11 10:04 UTC, hsgwa commented on ros2caret/verb/record.py
> +        print(f'{caret_node_num} recordable processes found.',)
@keita1523 
self._node_names doesn't indicate total number of nodes.
node names are filterd in : https://github.com/tier4/ros2caret/pull/48/files#diff-0f176304fda4d36231b3807c84626f734e976d56771cfe9f4857ba8f92c65e7bR62

caret_nodes run in each process with LD_PRELOAD.
So, caret_node_num indicates process number.

2022-11-11 10:06 UTC, hsgwa commented on ros2caret/verb/record.py
> +        print(f'{caret_node_num} recordable processes found.',)
For just an idea, `6 recordable nodes found` is more readable.
However, implementhing `Counting recordable nodes` feature may be next feature because it's needs modification.

2022-11-14 04:52 UTC, keita1523 commented
@hsgwa 
Running test is OK.
But I have one question.
I recorded caret demos from first and from middle. (
And, I created architecture files with each tracedata (hereinafter referred to as `first tracedata` and `middle tracedata`).
I couldn't use the architecture file generated with `first tracedata` to visualize `middle tracedata`.
It is OK?
Each data and file is [here](https://drive.google.com/drive/folders/1ZTdmXZhFTliLRRipcbX6kN6KCJblnc73).

2022-11-14 06:29 UTC, hsgwa commented
@keita1523 
Thank you for pointing out!
It seems an issue. I'll investigate it.

> I couldn't use the architecture file generated with first tracedata to visualize middle tracedata.

2022-11-17 05:04 UTC, hsgwa commented
@keita1523 
Both caret_trace and caret_analyze are updated to solve the issue you reported.

- https://github.com/tier4/CARET_trace/pull/68
- https://github.com/tier4/CARET_analyze/pull/190

Could you review them again?

2022-11-23 03:45 UTC, keita1523 requested changes
@hsgwa 
I confirmed the problem of Architecture file was resolved.
But, when I visualized callback scheduling, the timer callback started before red arrows. 

![image](https://user-images.githubusercontent.com/45618513/203465387-6e000b90-c199-4533-b186-ce29edf1fafd.png)

2022-11-23 21:24 UTC, hsgwa commented
@keita1523 
Are the CARET_trace and CARET_analyze branches up to date?
As you pointed out, the timer firing timing could be incorrect, and I've already tried to fix that.

- `9fa7170` in https://github.com/tier4/CARET_trace/pull/68
- `a96afd9` in https://github.com/tier4/CARET_analyze/pull/190

> the timer callback started before red arrows.

2022-12-01 07:23 UTC, takeshi-iwanari submitted a review, later dismissed
I confirmed this feature works with Autoware.Universe

2022-12-02 02:23 UTC, hsgwa commented
The reason pytest is failing is that github action runs on ubuntu 20.04.
I'll send another PR on this.
Anyway,  pytest passed locally.

2022-12-15 09:24 UTC, takeshi-iwanari approved these changes
I confirmed this feature works with Autoware.Universe

2022-12-16 00:19 UTC, keita1523 approved these changes
LGTM

2022-12-16 04:24 UTC, merged