Feat/caret version
tier4/ros2caret pull request #69
Opened 2023-04-29 14:03 UTC by taro-yu

## Description

## Related links

## Notes for reviewers

## Pre-review checklist for the PR author

- [ ] I've confirmed the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [ ] The PR is ready for review.

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

2023-05-01 07:57 UTC, nabetetsu commented on .github/workflows/update-caret-version.yml
> +          git commit -m "Update version to $latest_tag"
How would you like to add '-s' option for adding Signed-off-by trailer?

2023-05-08 07:14 UTC, atsushi421 requested changes
@taro-yu 
Please fix the warnings in pre-commit.ci.
https://results.pre-commit.ci/run/github/407361190/1683022562.GyvRrAlrQsicbNT1Phzo-w

2023-05-08 07:14 UTC, atsushi421 commented on ros2caret/verb/version.py
> +        setup_path = os.path.join(parent_dir, 'setup.py')
```suggestion
        setup_path = f"{os.path.dirname(os.path.abspath(__file__))}/../../setup.py"
```

2023-05-08 07:14 UTC, atsushi421 commented on ros2caret/verb/version.py
> +                    version = version.strip()
I think it would be clearer to print `version='v0.4.8'` as follows.

```suggestion
                    version = line.replace(',', '').strip()
```

2023-05-12 07:17 UTC, atsushi421 approved these changes
LGTM!

2023-05-12 07:53 UTC, rokamu623 commented on ros2caret/verb/version.py
> +                    print(version)
How about implementing it in this way? (Lines 27 ~ 30):

```python
import re

version = re.search("version='(.*)',", line)

if version is not None:
  print(version.group(1))
else:
  # error handling
```

2023-05-12 08:00 UTC, rokamu623 commented on ros2caret/verb/version.py
> +                    break
How about implementing it in this way? (Lines 26 ~ 31):

```python
import re

for line in file:
  version = re.search("version='(.*)',", line)
  if version is not None:
    print(version.group(1))
    break
```

2023-05-15 01:52 UTC, takeshi-iwanari requested changes
It's better to remove `tier4/ros2caret` from the script.
Using `${GITHUB_REPOSITORY}` might be a solution, or you can set a new variable for it at the beginning of the script.

2023-05-15 01:52 UTC, takeshi-iwanari commented on .github/workflows/update-caret-version.yml
> +          latest_tag=$(curl -s https://api.github.com/repos/tier4/ros2caret/tags | jq -r .[0].name)
Why don't you use environmental variable so that this script becomes more general.
```suggestion
          latest_tag=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/tags | jq -r .[0].name)
```

2023-05-15 01:52 UTC, takeshi-iwanari commented on .github/workflows/update-caret-version.yml
> +          repository: tier4/ros2caret
Why don't you remove this line so that this script becomes more general. ( can be used for another reposigory )
```suggestion
```

2023-05-15 01:59 UTC, takeshi-iwanari commented on .github/workflows/update-caret-version.yml
> +          latest_tag=$(curl -s https://api.github.com/repos/tier4/ros2caret/tags | jq -r .[0].name)
Or, you can just use `${GITHUB_REF_NAME}` variable instead of `latest_tag`

2023-05-15 02:05 UTC, takeshi-iwanari requested changes

2023-05-15 02:05 UTC, takeshi-iwanari commented on .github/workflows/update-caret-version.yml
> +          git commit -m "Update version to $latest_tag" -s
Could you follow the convention for commit message?
```suggestion
          git commit -m "chore: update version to $latest_tag" -s
```

2023-05-30 03:22 UTC, rokamu623 reviewed
LGTM!

However, please get approval from the other reviewers before merging.

2023-05-31 04:56 UTC, takeshi-iwanari requested changes

2023-05-31 04:56 UTC, takeshi-iwanari commented on .github/workflows/update-caret-version.yaml
> +          sed -i "s/__version__=.*/__version__='${{steps.tag.outputs.TAG_NAME}}'/" ros2caret/__version__.py
You need a space before/after `=` . Otherwise, replace will fail

2023-05-31 05:53 UTC, taro-yu commented on .github/workflows/update-caret-version.yaml
> +          sed -i "s/__version__=.*/__version__='${{steps.tag.outputs.TAG_NAME}}'/" ros2caret/__version__.py
@takeshi-iwanari 
I have fixed the error. Please check it.

2023-05-31 06:01 UTC, takeshi-iwanari commented on .github/workflows/update-caret-version.yaml
> +          sed -i "s/__version__=.*/__version__='${{steps.tag.outputs.TAG_NAME}}'/" ros2caret/__version__.py
@taro-yu 
You also need space after `=`

2023-05-31 06:07 UTC, takeshi-iwanari commented on .github/workflows/update-caret-version.yaml
> +          sed -i "s/__version__=.*/__version__='${{steps.tag.outputs.TAG_NAME}}'/" ros2caret/__version__.py
@taro-yu 
LGTM

2023-05-31 06:11 UTC, takeshi-iwanari requested changes
- Problem for sed command was fixed
- However, when you checkout a tag (e.g. v0.5.5), the value of version remains the previous value (e.g. v0.5.4)

2023-05-31 07:39 UTC, taro-yu commented
@takeshi-iwanari 
Sorry, I missed this one. Corrected.

> However, when you checkout a tag (e.g. v0.5.5), the value of version remains the previous value (e.g. v0.5.4) as I commented in JIRA

2023-06-05 06:52 UTC, takeshi-iwanari approved these changes
LGTM

2023-06-05 07:19 UTC, takeshi-iwanari requested changes
I found one concern.
Could you check it? and please fix it if it doesn't work as expected

2023-06-05 07:19 UTC, takeshi-iwanari commented on .github/workflows/update-caret-version.yaml
> +              if [[ -z $max_version || $version > $max_version ]]; then
Did you confirm if it works with a version string which has 2+ digits like `0.4.10` .
When I tested locally, it doesn't work...

```
A=0.4.8
B=0.4.9
if [[ $A > $B ]]; then echo "A>B"; else echo "A<B"; fi
> A<B

A=0.4.8
B=0.4.8.1
if [[ $A > $B ]]; then echo "A>B"; else echo "A<B"; fi
> A<B

A=0.4.8
B=0.4.10
if [[ $A > $B ]]; then echo "A>B"; else echo "A<B"; fi
> A>B
```

2023-06-05 11:59 UTC, taro-yu commented on .github/workflows/update-caret-version.yaml
> +              if [[ -z $max_version || $version > $max_version ]]; then
@takeshi-iwanari 
I fixed it.
Slightly more significant change, but I have changed to using the IFS command, where each number in the version information is divided into an array by period '.' and evaluate each of them. This ensures that the latter is correctly judged to be larger when evaluating 0.4.9 and 0.4.10.

The version information has also been changed so that it can be compared up to four digits. For example, if `rc/v0.4.9` and `rc/v0.4.9.1` are compared, the latter is selected.

2023-06-12 05:46 UTC, takeshi-iwanari commented on .github/workflows/update-caret-version.yaml
> +              if [[ -z $max_version || $version > $max_version ]]; then
@taro-yu 
Thank you for fixing it. The new logic looks okay, but could you create BRANCH_NAME using TAG_NAME (e.g. `BRANCH_NAME=rc/$TAG` ) so that we don't need the logic to create BRANCH_NAME any more, and BRANCH_NAME and TAG_NAME are always in pairs.
It has an advantage. In case the found BRANCH_NAME is wrong (it may be caused by bug in the logic or failure of creating rc/v... branch. also, an operator may forget to create a branch when creating a tag), this workflow modify wrong branch. If we create BRANCH_NAME fron TAG_NAME, we can avoid it and can notice it since the workflow will fail when checkouting to the branch.

2023-06-12 06:41 UTC, taro-yu commented on .github/workflows/update-caret-version.yaml
> +              if [[ -z $max_version || $version > $max_version ]]; then
@takeshi-iwanari 
I have fixed it.
The method for retrieving tags and branch names has been changed to the following simplified method:
`tag=$(curl -s https://api.github.com/repos/${GITHUB_REPOSITORY}/tags | jq -r .[0].name)
        branch=rc/$tag
        echo "TAG_NAME=$tag" >> "$GITHUB_OUTPUT"
        echo "BRANCH_NAME=$branch" >> "$GITHUB_OUTPUT"`

2023-06-13 04:11 UTC, takeshi-iwanari requested changes
Considering the following case, it would be better just to use the new tag name rather than finding the latest tag name.

- For example, the current tag is v0.4.15
- We needed to modify the previous version like v0.4.14 to v0.4.14.1 for bug hot fix
- When we do `git tag v0.4.14.1` , the current workflow will modify `v0.4.15` because `v0.4.15` is the latest one, but we want to modify `v0.4.14.1`
- Also, in this case, we don't want to modify the version in main branch, so I added if condition in the step to create PR

2023-06-13 04:11 UTC, takeshi-iwanari commented on .github/workflows/update-caret-version.yaml
> +                       --head ${{ steps.tag.outputs.BRANCH_NAME }}
```suggestion
          if [ ${{ steps.tag.outputs.LATEST_TAG_NAME }} == ${{ steps.tag.outputs.TAG_NAME }} ]; then
            gh pr create --title "chore: update version to ${{ steps.tag.outputs.TAG_NAME }}" \
                        --body "This pull request updates the version in __version__.py to ${{ steps.tag.outputs.TAG_NAME }}" \
                        --base main \
                        --head ${{ steps.tag.outputs.BRANCH_NAME }}
          fi
```

2023-06-13 04:11 UTC, takeshi-iwanari commented on .github/workflows/update-caret-version.yaml
> +      - name: Create PR to main branch
```suggestion
      - name: Create PR to main branch if the created tag is the latest
```

2023-06-13 08:54 UTC, takeshi-iwanari commented
@taro-yu 
> Lastly, I would like to confirm that, for example, when latest_tag=v0.4.15 and currend_tag=v0.4.14.1, is it correct that the version information is updated in rc/v0.4.14.1 and v0.4.14.1, and the last PR creation step is not executed?

"currend_tag" means the tag you are creating (`git tag v0.4.14.1 & git push v0.4.14.1`), right? If so, Correct!

2023-06-13 09:07 UTC, taro-yu commented
@takeshi-iwanari 

> "currend_tag" means the tag you are creating (git tag v0.4.14.1 & git push v0.4.14.1), right?
I thought in this way!

2023-06-13 09:29 UTC, takeshi-iwanari submitted a review, later dismissed
LGTM!

2023-06-13 10:00 UTC, takeshi-iwanari approved these changes
LGTM

2023-06-13 10:02 UTC, merged