feat: CLI for batch check and summary display
tier4/ros2caret pull request #7
Opened 2022-05-09 07:27 UTC by atsushi421

@hsgwa 
お疲れ様です。
[測定後の一括チェックツール作成](https://tier4.atlassian.net/browse/T4PB-17109)が完了したので、ご確認をお願いいたします。

lttng クラスを初期化する際に、Event_Counter クラスの [_validate](https://github.com/tier4/CARET_analyze/blob/f79dfe49c6cbeb81efd8223c6bb41f20b99f74a4/caret_analyze/infra/lttng/event_counter.py#L44) が実行され、LD_PRELOAD によるトレースポイントが入っているかのチェックも実施されるので、特にこのチェックに関して追加実装は不要でした。

サマリ表示では、-c オプションでチェックも兼ねることができるようになっています。（[こちらのスレッドの内容](https://emb4hq.slack.com/archives/C017YM4AA06/p1650940805273969?thread_ts=1650616341.892579&cid=C017YM4AA06)）
また、`lttng.get_count(groupby=['node_name'(または 'topic_name')]) `で取得できる dataframe の "topic_name" や "node_name" が "-" となっている行に関しては、値が取得できなかったものの総和になってしまうと考えたため、表示していません。

以下はコマンド実行時の出力結果です。
https://drive.google.com/drive/folders/1FX67Gl7DF9Jgw7sZorCBKNHyiyDJ5BwV?usp=sharing

2022-05-10 01:35 UTC, hsgwa requested changes

2022-05-10 01:35 UTC, hsgwa commented on ros2caret/verb/node_summary.py
> +from tabulate import tabulate
新規にサードパーティーのパッケージを使っているようですので、
package.xmlにもtabulateの追加をお願いできますででしょうか？

https://github.com/ros/rosdistro/blob/master/rosdep/python.yaml#L4956

既に rosdepに記載があるので、rodep update &&rosdep installでインストールされるようになるはずです。

パッケージの追加については、ドキュメントやCI等にも対応が必要になってしまうので、先日のミーティングで話が挙がったように一旦別リポジトリにまとめる等で対応が必要になりますね。

2022-05-16 00:52 UTC, atsushi421 commented on ros2caret/verb/node_summary.py
> +from tabulate import tabulate
追加させていただきました。
ご確認お願いいたします。

2022-05-16 03:55 UTC, hsgwa approved these changes
はい、ありがとうございます。
良さそうですのでマージします。

2022-05-17 09:10 UTC, merged